<h1 class="mb-3">REGULATION OF THE PROMOTION OF SINGLE, RECURRING OR REWARD DONATION:</h1>
<p>By joining the PROMOTION through the RecNet website or supporting partners, the participant must read and accept the Regulation of the Promotion DONATION SINGLE, RECURRING OR PREMIABLE, hereinafter referred to as "Promotion", promoted by RECNET LTDA, a legal entity of private law, registered in the CNPJ/MF under no. 68.516.962/0001-31, with headquarters at Rua Universo, 21, 4th floor, Santa Lúcia neighborhood, Belo Horizonte, Minas Gerais, in partnership with ChildFund Brasil, registered with CNPJ under no. 172719.25.0001/70, Exempt State Registration, headquartered at Rua Curitiba, no. 689, fifth floor, Bairro Centro, in the city of Belo Horizonte, Minas Gerais, hereinafter all called "Promotoras" whose focus will be the Customers of Associates of Class Business Entities of the State of Minas Gerais and other donors or stores not linked to entities and who adhere to the Promotion and whose participation is visible through signaling at the respective points of sale (physical or electronic) of products and / or services in the locations of the State of Minas Gerais , hereinafter simply referred to as "Participating Members". </p>

<p><strong>1. CHARACTERIZATION: </strong></p>
<p>1.1. The Promotion is directed, preferably, but not restricted to the Clients of RECNET Members, whether legal or physical entities, over 18 (eighteen) years, provided that residents and/or domiciled in national territory, are holders of CPF and who are holders of CPF and RG, herein after "Participating Clients".</p>
<p>1.2. The promotion is carried out by RECNET and regulated by the partnership and service provision contract signed by RECNET and CHILD FUND BRASIL.</p>
<p>1.3 This Promotion is freely available for prizes by drawing durable or consumer goods that may be made available by Participating Members and which will be informed by e-mail by RecNet and Participating Associations and, when they are prizeable in cash, by donation of change at points of sale, they will be part of a specific regulation and will be based on Capitalization Bonds, incentive mode, along the lines of Decree No. 6,388 of March 5, 2008 and its regulation.</p>
<p>1.4. In this case, Incentive Type Capitalization Securities issued by a First Line insurer whose contract, at the time of product launch, will be made available for reading on the recnet and participating associates’ website and managed by it according to the SUSEP Process – Superintendence of Private Insurance of Brazil and acquired for the campaign.</p>
<p>1.5. The result, for prize purposes, will be depending on the result of the extraction of the Federal Lottery, in the form established in the Technical Note of the Capitalization Title mentioned above and that will be disclosed on the websites and points of sale, according to the criteria required by SUSEP.</p>
<p>1.6. Participation in the Promotion is voluntary and is not subject to the prior authorization established in Law No. 5,768/71 and related legislation.</p>

<p><strong>2. PURPOSE AND RESULT OF THE PROMOTION: </strong></p>
<p>The Promotion aims to raise funds for donation to support the social actions promoted by ChildFund Brazil.</p>
<p>70% (seventy percent) of the net income obtained through this campaign will be reverted to child fund Brasil's shares when it is a direct, single or recurring donation and 50% (fifty percent) when it is backed by capitalization securities.</p>

<p><strong>3. FORM OF PARTICIPATION: </strong></p>
<p>3.1. The promotion begins on 01/04/2021 and indeterminate duration and prizes in material goods or services will be constantly informed as they become available. A coupon number for the contest(s) will be issued for each donation made, either directly or for change and will be measured by comparison with the numbers drawn by the Brazilian Federal Lottery, on the dates shown in the coupon, according to the results obtained through the units of the first five numbers of the Federal Lottery extraction, read from the first to the fifth prizes.</p>
<p>3.2. Coupons always compete for saturday's draw on the dates reported on the coupon.</p>
<p>3.3. For the purposes of this Promotion, all customer service channels of participating members will be considered.</p>
<p>3.4. The client may choose to participate in the campaign, donating any amount above R$ 5.00 (five reais) in the case of direct donation and, in the case of Remarketable Change, From R$ 1.01 (one reais and one cent) to R$ 9.99 (nine reais of ninety-nine cents).</p>
<p>3.5. TO PARTICIPATE, it is sufficient for the customer to go to one of the stores of the Participating Members and /or on their respective websites or on the RECNET website and choose to participate in this campaign, contributing to child fund, with some value quoted in item 3.4, in kind, or by credit card accepted in the establishment or website, following the procedures as described in item 3.1 and subsequent to these Regulations, with which the Participating Client must be fully agreed.</p>
<p>3.6 When making your contribution through a POS equipment, intended exclusively, or not, for the operation of this promotion, developed by the Promoter RECNET or integrated through the POS of the Participant's own participant of this promotion, a proof of participation will be issued, with the respective lucky number, the series to which it is linked and the date of the draw. In addition, the legal data of the company issuing the capitalization securities will also appear, when this is the modality, its CNPJ and the number of the Administrative Process SUSEP, referring to this capitalization.</p>

<p><strong>4. DRAW NUMBER </strong></p>
<p>4.1 In the case of participation with the variable value donation, between R$ 1.01 (one reais and one cent of real) and R$ 9.99 (nine reais and ninety-nine cents) described in item 3.1.5 above, the Participating Client will receive 01 (one) coupon per donation or for exchange that can be replaced by the terms and conditions set forth in the legislation and provided for in these Regulations.</p>
<p>4.2 Each Lucky Number will be valid for the Sweepstakes valid in accordance with this Regulation. Participating Customers will be able to track the validity of each of their lucky numbers received and the results of the Sweepstakes at the www.recnet.com.br/doacoes/</p>
<p>4.3 The Participating Customers express their total and unconditional acceptance of the provisions of these Regulations, as well as waive, from the outset, any questioning about the judgment criteria adopted.</p>

<p><strong>5. Awards:</strong></p>
<p>5.1 The winner shall be the one who has exactly the lucky number coincident with the number determined according to the rules described in item 6 of these Regulations.</p>
<p>5.2 All winners must contact the Promoter company to receive the prize to which they are entitled, by registering on the www.recnet.com.br website within 90 (ninety) days of the draw date.</p>
<p>5.3 RecNet will deliver the prizes to the Winning Participating Customers, within a maximum of fifteen (15) business days, counted from the date of contact with the winner of each draw, and the winner of each draw, and the winner must provide: Coupon received at the time of donation, copy of his CPF, his/her id card, all valid and proof of his residence updated (previous 180 days ago), as well as signing a receipt relating to the prize amount. The amount will be received by the winners by means of a bank deposit in a checking account or savings of their ownership, and it is mandatory that the winner informs their bank details, in due course. If the prize is deposited in the current account of the lucky one, the deposit receipt will be considered the receipt of receipt of the prize, without the signature of the receipt by the drawn.</p>
<p>5.4 The premiums, when in kind, will already be paid net of Income Tax, incident at the rate of 25% (twenty-five percent) and whose complete regulation and normalized by SUSEP, will be informed at the time of its launch.</p>
<p>5.5 Winning Customers, upon receiving their prize, agree to accept it, without the right to future claims, as well as agreeing to exempt the Promoters and/or any company involved in the Promotion, their affiliated companies, subsidiaries and affiliates, including their respective employees, representatives, service providers and agents or any other person or organization directly or indirectly involved in this Promotion, from any and all claim or legal action resulting from their participation in the Promotion or receipt and use of any award, except those relating to compliance, good progress and outcome of the Promotion.</p>

<p><strong>6. Counting:</strong></p>
<p>6.1. During the term of this Promotion, the winning Participating Customers will be raffle, according to the dates described in item 5.1 above.</p>
<p>A. To compete, each participant will have a lucky number, random and predetermined, (for each donation or change according to item 4.1) not repeated in the same series of Titles, composed of 05 (five) digits and between 00,000 (inclusive) and 99,999 (inclusive), totaling 100,000 (one hundred thousand) numbers each series.</p>
<p>B. In the draw will be considered the 05 (five) first prizes of the extraction of the Federal Lottery from the date reported in the coupon, in order of prize. Lucky Numbers will be obtained as follows:</p>
<p>b.1. The number obtained by reading, from top to bottom, the units of the first five prizes of the federal lottery extraction of the date referenced in item 5.1 above will be calculated.</p>
<p>For example, the federal lottery extraction should be as follows:<br />
1. 1st prize = 4 5 8 0 4<br />
2. 2nd prize = 5 6 9 5 4<br />
3. 3rd prize = 5 3 0 0 8<br />
4. 4th prize = 4 0 1 4 3<br />
5. 5th prize = 3 0 1 2 6</p>
<p><strong>- Lucky number contemplated in this example is: 44,836</strong></p>
<p>6.2. If any Draw Number has not been distributed in any of the draws, there will be no distribution of that prize and will not be accumulated for the next draw.</p>
<p>6.3. If any extraction of the Federal Lottery does not occur on any of the scheduled dates, for any reason, the date of the subsequent Federal Lottery extraction that may be held by it will be considered for the purposes of ascertaining the result of this Promotion.</p>
<p>6.4. If Caixa Econômica Federal definitively suspends the extractions of the Federal Lottery, or modifies these extractions in a way that no longer coincides with the draw rules established in these General Conditions, or there is any impediment to the binding of the Federal Lottery to the draws provided for in these General Conditions, the Capitalization Company, within a maximum of 90 (ninety) days, will promote the draw not held with its own devices and in a place of free access to the public under independent audit supervision and under the same conditions as foreseen in the previous items, giving prior and wide dissemination of the fact.</p>
<p>6.5. In the case of Corporate Participating Clients, the prize will be deposited in the current account held by the awarded legal entity.</p>

<p><strong>7. Disclosure: </strong></p>
<p>7.1. The results of the sweepstakes will be widely disseminated to Participating Members and Class Business Entities, through the co-promoter websites of this promotion. After the identification of the winners, they will have their names disclosed on the www.recnet.com.br.</p>
<p>7.2. If the winners are unable to locate, the prize will remain valid for 90 (ninety) days. After this period, the winner's right to the prize will expire.</p>
<p>7.3. This Regulation is available for consultation by anyone interested in the www.recnet.com.br/ websites and partner websites.</p>

<p><strong>8. GENERAL PROVISIONS: </strong></p>
<p>8.1. Winning Participating Customers agree to assign in this act, free of charge, the rights to use their names, images and voice sounds to the Promoters, in any media (printed or electronic, CD, DVD, magazines, newspapers, internet sites, social networks, open or closed TV, in addition to radios), for exclusive use in the dissemination of this Promotion, for a period of twelve (12) months from the date of receipt of the prize.</p>
<p>8.2. Participating Customers may be automatically excluded from this Promotion in case of suspected fraud or proven fraud, and may also be responsible for a crime of ideological or documentary falsehood, not fulfilling the requirements previously determined and/or due to incorrect or erroneous information, in accordance with the rules of this Regulation.</p>
<p>8.3. At no time may the Promoter be liable for lost, delayed, erroneously submitted, incomplete, incorrect, invalid or inaccurate entries. The Promoter shall not be liable for problems, failures or technical functioning, of any kind, on computer networks, servers or providers, computer equipment, hardware or software, or error, interruption, defect, delay or failure in operations or transmissions for the correct processing of subscriptions, including, but not limited to, the inaccurate transmission of registrations or failure of the Promoter to receive them, due to technical problems, congestion on the Internet or on the site linked to the Promotion, viruses, programming failure (bugs) or violation by third parties (hackers), of which they have no control.</p>
<p>8.4. The Promoter reserves the right to disqualify any Participating Customer who deems to be manipulating the operation of this Promotion or in violation of the terms and conditions set out in these Regulations.</p>
<p>8.5. Nor will the Promoter be responsible for misplaced, incomplete or damaged data that make it impossible to deliver the prizes, including the loss of the original coupon printed at the time of participation in the campaign.</p>
<p>8.6. It will be exclusively up to the Promoter, through an independent commission, to evaluate and decide on the omitted cases and doubts raised during the promotion, and its decisions are sovereign and irreable.</p>
<p>8.7. The mere participation presupposes full knowledge and agreement with the provisions of these Regulations by the Participating Customers. Participating Customers expressly acknowledge and accept that the Promoter cannot be held liable for any damage or injury arising from participation in this Promotion or any acceptance of the prize.</p>
<p>8.8. The approval of the capitalization securities by SUSEP does not imply, by the Municipality, in incentive or recommendation their acquisition, representing, exclusively, their adequacy to the rules in force.</p>

<p><strong>9. Forum </strong></p>
<p>9.1. The Forum of the District of Belo Horizonte, MG is elected to resolve any issues arising from these Regulations. Any dispute arising under these Regulations will be governed by Brazilian law.</p>

<p><strong>Belo Horizonte, March 1, 2021. </strong></p>