<h1 class="mb-3">REGULAMENTO DA PROMOÇÃO DOAÇÃO ÚNICA, RECORRENTE OU PREMIÁVEL:</h1>
<p>Ao aderir à PROMOÇÃO pelo site da RecNet ou de parceiros apoiadores, o participante deverá ler e aceitar o Regulamento da Promoção DOAÇÃO ÚNICA, RECORRENTE OU PREMIÁVEL, doravante denominada "Promoção", promovida pela RECNET LTDA, pessoa jurídica de direito privado, inscrita no CNPJ/MF sob o nº 68.516.962/0001-31, com sede na Rua Universo, 21, 4º andar, bairro Santa Lúcia, Belo Horizonte, Minas Gerais, em parceria com a ChildFund Brasil, inscrita no CNPJ sob o no 172719.25.0001/70, Inscrição Estadual Isenta, sediada na Rua Curitiba, no. 689, quinto andar, Bairro Centro, na cidade de Belo Horizonte, Minas Gerais, doravante todas denominadas como "Promotoras" cujo foco serão os Clientes dos Associados das Entidades Empresariais de Classe do Estado de Minas Gerais e demais doadores ou lojas não vinculadas a entidades e que aderirem à Promoção e cuja participação esteja visível através de sinalização nos respectivos pontos de venda (físicos ou eletrônicos) de produtos e/ou serviços nas localidades do Estado de Minas Gerais, doravante denominados simplesmente “Associados Participantes”.</p>

<p><strong>1. CARACTERIZAÇÃO: </strong></p>
<p>1.1. A Promoção é direcionada, preferencialmente, mas não se restringindo aos Clientes dos Associados da RECNET, sejam pessoas jurídicas ou físicas, maiores de 18 (dezoito) anos, desde que residentes e/ou domiciliadas em território nacional, sejam portadores de CPF e que sejam portadores de CPF e RG, aqui denominados "Clientes Participantes".</p>
<p>1.2. A promoção é realizada pela RECNET e regulada pelo contrato de parceria e prestação de serviços assinado pela RECNET e CHILD FUND BRASIL.</p>
<p>1.3 Esta Promoção tem a distribuição gratuita de prêmios por meio de sorteio de bens duráveis ou de consumo que possam ser disponibilizados pelos Associados Participantes e que serão informados por e-mail pela RecNet e Associações Participantes e, quando forem premiáveis em dinheiro, por doação de troco nos pontos de venda, farão parte de regulamento específico e serão lastreado em Títulos de Capitalização, da Modalidade Incentivo, nos moldes do Decreto no 6.388, de 05 de março de 2008 e seu regulamento.</p>
<p>1.4. Neste caso serão utilizados Títulos de Capitalização da Modalidade Incentivo emitidos por seguradora de Primeira Linha cujo contrato, à época do lançamento do produto, será disponibilizado para leitura no site da RecNet e Associados Participantes e gerenciados por ela conforme Processo SUSEP – Superintendência de Seguros Privados do Brasil e adquiridos para a campanha.</p>
<p>1.5. O resultado, para fins de premiação, será decorrente do resultado da extração da Loteria Federal, na forma estabelecida em Nota Técnica do Título de Capitalização acima referido e que será divulgado nos sites e pontos de venda, conforme os critérios exigidos pela SUSEP.</p>
<p>1.6. A participação na Promoção é voluntária e não está subordinada à autorização prévia estabelecida na Lei nº 5.768/71 e legislação correlata.</p>

<p><strong>2. OBJETIVO E RESULTADO DA PROMOÇÃO: </strong></p>
<p>2.1. A Promoção visa arrecadar fundos para doação para suporte às ações sociais promovidas pela ChildFund Brasil.</p>
<p>2.2 70% (setenta por cento) do resultado líquido obtido por meio desta campanha será revertido para as ações sociais da Child Fund Brasil quando for doação direta, única ou recorrente e 50% (cinquenta por cento) quando for lastreada por títulos de capitalização.</p>

<p><strong>3. FORMA DE PARTICIPAÇÃO: </strong></p>
<p>3.1. A promoção tem início no dia 01/04/2021 e duração indeterminada e os prêmios em bens materiais ou serviços, serão constantemente informados à medida em que forem sendo disponibilizados. Um número de cupom para o (s) concurso (s) será emitido para cada doação feita, seja direta ou por troco e será aferido por comparação com os números sorteados pela Loteria Federal do Brasil, nas datas mostradas no cupom, de acordo com os resultados obtidos por meio das unidades dos cinco primeiros números da extração da Loteria Federal, lidos do primeiro ao quinto prêmios. </p>
<p>3.2. Os cupons sempre concorrem ao sorteio do sábado nas datas informadas no cupom. </p>
<p>3.3. Para fins desta Promoção, serão considerados todos os canais de atendimento aos Clientes dos Associados Participantes. </p>
<p>3.4. O cliente poderá optar por participar da campanha, doando qualquer valor acima de R$5,00 (cinco reais) no caso de doação direta e, no caso de Troco Premiável, De R$1,01 (um real e um centavo) a R$9,99 (nove reais de noventa e nove centavos). </p>
<p>3.5. PARA PARTICIPAR, basta que o cliente vá a uma das lojas dos Associados Participantes e /ou nos seus respectivos sites ou no site da RECNET e opte por participar desta campanha, contribuindo para a Child Fund, com algum valor citado no item 3.4, em espécie, ou mediante cartão de crédito aceito no estabelecimento ou site, seguindo os procedimentos conforme descrito no item 3.1 e subsequentes deste Regulamento, com o qual o Cliente Participante deverá estar integralmente de acordo. </p>
<p>3.6 Ao fazer sua contribuição através de um equipamento POS, destinado exclusivamente, ou não, para a operacionalização desta promoção, desenvolvido pela Promotora RECNET ou integrado através do próprio PDV do Associado Participante desta promoção, será emitido um comprovante de participação, com o respectivo número da sorte, a série a que está vinculada e data do sorteio. Ademais, constarão também, os dados legais da empresa emissora dos títulos de capitalização, quando for essa a modalidade, o seu CNPJ e o número do processo administrativo SUSEP, referente a esta capitalização. </p>

<p><strong>4. NÚMERO PARA SORTEIO </strong></p>
<p>4.1 No caso de participação com a doação de valor variável, entre R$ 1,01 (um real e um centavo de real) e R$ 9,99 (nove reais e noventa e nove centavos) descrito no item 3.1.5 acima, o Cliente Participante receberá 01 (um) cupom por doação ou por troco premiável nos termos e condições estabelecidos na legislação e previstos neste Regulamento. </p>
<p>4.2 Cada Número da sorte terá validade para os Sorteios válidos de acordo com este Regulamento. Os Clientes Participantes poderão acompanhar a validade de cada um dos seus números da sorte recebidos e os resultados dos Sorteios no endereço www.recnet.com.br/doacoes/ </p>
<p>4.3 Os Clientes Participantes manifestam sua total e incondicional aceitação ao disposto neste Regulamento, bem como renunciam, desde logo, a qualquer questionamento sobre os critérios de julgamento adotados. </p>

<p><strong>5. PREMIAÇÃO: </strong></p>
<p>5.1 O ganhador será aquele que possuir exatamente o número da sorte coincidente com o número apurado de acordo com as regras descritas no item 6, deste Regulamento.</p>
<p>5.2 Todos os ganhadores deverão entrar em contato com a empresa Promotora para receber o prêmio a que têm direito, mediante cadastro no site www.recnet.com.br no prazo de até 90 (noventa) dias da data do sorteio.</p>
<p>5.3 A RecNet efetuará a entrega dos prêmios aos Clientes Participantes Ganhadores, no prazo máximo de 15 (quinze) dias úteis, contados da data de contato com o ganhador de cada sorteio, sendo que este deverá fornecer: Cupom recebido no momento da doação, cópia de seu CPF, de sua cédula de identidade, todos válidos e do comprovante de sua residência atualizado (anterior há 180 dias), bem como assinar um recibo relativo ao valor do prêmio. O valor será recebido, pelos ganhadores, por meio de depósito bancário em conta-corrente ou poupança de sua titularidade, sendo obrigatório que o ganhador informe os seus dados bancários, oportunamente. Se o prêmio for depositado em conta corrente do próprio sorteado, o recibo de depósito será considerado o recibo de recebimento do prêmio, dispensando a assinatura do recibo pelo sorteado.</p>
<p>5.4 Os prêmios, quando em espécie, serão pagos já líquidos de Imposto de Renda, incidente à alíquota de 25% (vinte e cinco por cento) e cujo regulamento completo e normalizado pela SUSEP, será informado por ocasião de seu lançamento.</p>
<p>5.5 Os Clientes ganhadores, ao receberem o seu prêmio, concordam em aceitá-lo, sem direito a futuras reivindicações, bem como concordam em isentar as Promotoras e/ou qualquer empresa envolvida na Promoção, suas companhias coligadas, subsidiárias e afiliadas, inclusive seus respectivos funcionários, representantes, prestadores de serviços e agentes ou qualquer outra pessoa ou organização envolvida diretamente ou indiretamente nesta Promoção, de toda e qualquer demanda ou ação legal consequente de sua participação na Promoção ou recebimento e utilização de qualquer prêmio, com exceção daquelas relativas ao cumprimento, bom andamento e desfecho da Promoção.</p>

<p><strong>6. APURAÇÃO: </strong></p>
<p>6.1. Durante a vigência desta Promoção, ocorrerá o sorteio dos Clientes Participantes ganhadores, conforme as datas descritas no item 5.1 acima.</p>
<p>a. Para concorrer, cada participante terá um número da sorte, aleatório e pré-determinado, (para cada doação ou troco conforme item 4.1) não repetido na mesma série de Títulos, composto de 05 (cinco) algarismos e compreendido entre 00.000 (inclusive) e 99.999 (inclusive), totalizando 100.000 (cem mil) números a cada série.</p>
<p>b. No sorteio serão considerados os 05 (cinco) primeiros prêmios da extração da Loteria Federal da data informada no cupom, observada a ordem de premiação. Os Números da sorte serão obtidos da seguinte maneira:</p>
<p>b.1. Será apurado o número obtido por meio da leitura, de cima para baixo, das unidades dos cinco primeiros prêmios da extração da Loteria Federal da data referenciada no item 5.1 acima.</p>
<p>A título de exemplo, considere-se que a extração da Loteria Federal seja a seguinte:<br />
1. 1º prêmio = 4 5 8 0 4<br />
2. 2º prêmio = 5 6 9 5 4<br />
3. 3º prêmio = 5 3 0 0 8<br />
4. 4º prêmio = 4 0 1 4 3<br />
5. 5º prêmio = 3 0 1 2 6<br /></p>
<p><strong>- Número da sorte contemplado, neste exemplo, é o: 44.836 </strong></p>
<p>6.2. Na eventualidade de algum Número para Sorteio não ter sido distribuído em qualquer dos sorteios, não haverá a distribuição daquele prêmio e não será acumulado para o próximo sorteio.</p>
<p>6.3. Caso alguma extração da Loteria Federal não venha a ocorrer em qualquer das datas previstas, por qualquer motivo, será considerada para efeitos de apuração do resultado desta Promoção, a data da extração da Loteria Federal subsequente que vier por ela a ser realizada.</p>
<p>6.4. Caso a Caixa Econômica Federal suspenda definitivamente as extrações da Loteria Federal, ou modifique as referidas extrações de forma que não mais coincidam com as regras de sorteio estabelecidas nestas Condições Gerais, ou haja qualquer impedimento à vinculação da Loteria Federal aos sorteios previstos nestas Condições Gerais, a Sociedade de Capitalização, num prazo máximo de 90 (noventa) dias, promoverá o sorteio não realizado com aparelhos próprios e em local de livre acesso ao público sob fiscalização de auditoria independente e nas mesmas condições previstas nos itens anteriores, dando prévia e ampla divulgação do fato.</p>
<p>6.5. No caso de Clientes Participantes pessoas jurídicas, o prêmio será depositado em conta-corrente de titularidade da pessoa jurídica premiada.</p>

<p><strong>7. DIVULGAÇÃO: </strong></p>
<p>7.1. Os resultados dos sorteios serão amplamente divulgados nos Associados Participantes e Entidades Empresariais de Classe, por meio dos sites copromotores desta promoção. Após a identificação dos ganhadores, estes terão seus nomes divulgados no website www.recnet.com.br.</p>
<p>7.2. Caso haja a impossibilidade de localização dos ganhadores, a premiação permanecerá válida por 90 (noventa) dias. Após este prazo, caducará o direito do ganhador ao prêmio.</p>
<p>7.3. O presente Regulamento está disponível para consulta por qualquer interessado nos websites www.recnet.com.br/ e nos sites parceiros.</p>

<p><strong>8. DISPOSIÇÕES GERAIS: </strong></p>
<p>8.1. Os Clientes Participantes Ganhadores concordam em ceder neste ato, gratuitamente, os direitos de uso dos seus nomes, imagens e sons de voz às Promotoras, em quaisquer mídias (impressa ou eletrônica, CD, DVD, revistas, jornais, sites internet, redes sociais, TV aberta ou fechada, além de rádios), para uso exclusivo na divulgação desta Promoção, pelo período de 12 (doze) meses a contar da data de recebimento do prêmio.</p>
<p>8.2. Os Clientes Participantes poderão ser excluídos automaticamente desta Promoção em caso de suspeita de fraude ou fraude comprovada, podendo ainda responder por crime de falsidade ideológica ou documental, não preenchimento dos requisitos previamente determinados e/ou em decorrência de informações incorretas ou equivocadas, de acordo com as regras deste Regulamento.</p>
<p>8.3. Em momento algum poderá a Promotora ser responsabilizada por inscrições perdidas, atrasadas, enviadas erroneamente, incompletas, incorretas, inválidas ou imprecisas. A Promotora não será responsável por problemas, falhas ou funcionamento técnico, de qualquer tipo, em redes de computadores, servidores ou provedores, equipamentos de computadores, hardware ou software, ou erro, interrupção, defeito, atraso ou falha em operações ou transmissões para o correto processamento de inscrições, incluindo, mas não se limitando, a transmissão imprecisa de inscrições ou falha da Promotora em recebê-las, em razão de problemas técnicos, congestionamento na internet ou no site ligado à Promoção, vírus, falha de programação (bugs) ou violação por terceiros (hackers), dos quais não tenham qualquer controle.</p>
<p>8.4. A Promotora reserva-se no direito de desclassificar qualquer Cliente Participante que julgar estar manipulando a operação desta Promoção ou violando os termos e condições dispostos neste Regulamento.</p>
<p>8.5. Também não será a Promotora responsável por dados extraviados, incompletos ou danificados que impossibilitem a entrega dos prêmios, dentre eles, a perda do cupom original impresso no momento da participação na campanha.</p>
<p>8.6. Caberá exclusivamente à Promotora, por meio de uma comissão independente, avaliar e decidir sobre os casos omissos e as dúvidas suscitadas durante a realização da Promoção, sendo suas decisões soberanas e irrecorríveis.</p>
<p>8.7. A simples participação pressupõe total conhecimento e concordância com as disposições deste Regulamento, por parte dos Clientes Participantes. Os Clientes Participantes reconhecem e aceitam expressamente que a Promotora não poderá ser responsabilizada por qualquer dano ou prejuízo oriundo da participação nesta Promoção ou da eventual aceitação do prêmio.</p>
<p>8.8. A aprovação dos títulos de capitalização pela SUSEP não implica, por parte da Autarquia, em incentivo ou recomendação a sua aquisição, representando, exclusivamente, sua adequação às normas em vigor.</p>

<p><strong>9. DO FORO </strong></p>
<p>9.1. Fica eleito o Foro da Comarca de Belo Horizonte, MG para dirimir quaisquer questões oriundas deste Regulamento. Qualquer disputa que surja em virtude do presente Regulamento será regulada pela legislação brasileira. </p>
<p><strong>Belo Horizonte, 01 de março de 2.021. </strong></p>